# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Set branch name
        run: echo >>$GITHUB_ENV BRANCH_NAME=${GITHUB_REF#refs/heads/}
      - name: Echo branch name
        run: echo ${BRANCH_NAME}
      - name: Clone The Code
        run: git clone -b "${BRANCH_NAME}" git@github.com:openkraken/cli.git --depth=1 "${RUNNER_WORKSPACE}/cli_${BRANCH_NAME}";
      - run: cd ${RUNNER_WORKSPACE}/cli_${BRANCH_NAME} && sh build.sh
      - run: cd ${RUNNER_WORKSPACE}/cli_${BRANCH_NAME} && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.ACCESS_TOKEN}}
      - name: Clean Up
        run: rm -rf ${RUNNER_WORKSPACE}/cli_${BRANCH_NAME}
